# spring:
#   data:
#     mongodb:
#       uri: "mongodb+srv://nainglinthant1998:nainglinthant1998@customerdb0.jg9rnlh.mongodb.net/nainglinthant?retryWrites=true&w=majority"
#   mail:
#     host: smtp.gmail.com
#     port: 587
#     username: nainglinthant1998@gmail.com
#     password: gppifdgkizceawjd
#     properties:
#       mail:
#         smtp:
#           auth: true
#           starttls:
#             enable: true
# server:
#   port: 8080
#   servlet:
#     session:
#       timeout: 1800

