spring:
  data:
    mongodb:
      uri: "mongodb+srv://zinphoomonzpm:zinphoomonzpm@cluster0.fczgjro.mongodb.net/restaurant_db?retryWrites=true&w=majority&appName=Cluster0"
#   mail:
#     host: smtp.gmail.com
#     port: 587
#     username: nainglinthant1998@gmail.com
#     password: gppifdgkizceawjd
#     properties:
#       mail:
#         smtp:
#           auth: true
#           starttls:
#             enable: true
server:
  port: 8082
  servlet:
    session:
      timeout: 1800

