spring:
  data:
    mongodb:
      uri: "mongodb+srv://zinphoomon:zinphoomon@atlascluster.akcw5bt.mongodb.net/restaurant_db?retryWrites=true&w=majority&appName=AtlasCluster"

logging:
  level:
    org.mongodb.driver: DEBUG
#   mail:
#     host: smtp.gmail.com
#     port: 587
#     username: nainglinthant1998@gmail.com
#     password: gppifdgkizceawjd
#     properties:
#       mail:
#         smtp:
#           auth: true
#           starttls:
#             enable: true
# server:
#   port: 8080
#   servlet:
#     session:
#       timeout: 1800

